version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-225-116-36.compute-1.amazonaws.com
            database: d5qolv1ejvts82
            schema: public
            user: ebieelqwapqvtu
            password: 38a5cf0a60d600b24641bc968f8a30a3631e1cd6db2e371e683ad0bb9ff5ca87
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true